### ISSUE TITLE
Ekhel

### ISSUE THREAD

**Issue by Ekhel** [antheiz/antheiz#3]
Adik Theis Kirim nomor hape dulu

**Comment by yokoberek** [comment]
> Adik Theis Kirim nomor hape dulu

Halo kaks, sorry baru lihat ni heheh..
Ini sa nomor kaks: 082229369614

**Comment by antheiz** [comment]
> Adik Theis Kirim nomor hape dulu

Halo kaks @Ekhel, sorry baru lihat issue ni..
Ini sa nomor kaks: 082229369614
